services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        container_name: ${APP_NAME}-php
        build: .docker/php
        ports:
            - 5174:5173
        volumes:
            - .:/var/www:cached
        networks:
            - proxy-network

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        container_name: ${APP_NAME}-nginx
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
        networks:
            - proxy-network

    ####################################################################################################
    # DATABASE (MySQL)
    ####################################################################################################
    mysql:
        container_name: ${APP_NAME}-mysql
        image: mysql:8.1
        ports:
            - 3307:3306
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - proxy-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

    ####################################################################################################
    # phpMyAdmin
    ####################################################################################################
    phpmyadmin:
        container_name: ${APP_NAME}-phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8081:80
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
            PMA_ARBITRARY: 1
        volumes:
            - .docker/phpmyadmin/sessions:/sessions
        networks:
            - proxy-network

    ####################################################################################################
    # Adminer (Optional)
    ####################################################################################################
    # adminer:
    #     container_name: ${APP_NAME}-adminer
    #     image: adminer
    #     ports:
    #         - 9090:8080
    #     depends_on:
    #         - mysql
    #     networks:
    #         - proxy-network

    ####################################################################################################
    # Mailpit (Optional)
    ####################################################################################################
    # mail:
    #     container_name: ${APP_NAME}-mailpit
    #     image: axllent/mailpit:latest
    #     ports:
    #         - 8025:8025
    #         - 1025:1025
    #     networks:
    #         - proxy-network

    ####################################################################################################
    # Redis (Optional)
    ####################################################################################################
    # redis:
    #     container_name: ${APP_NAME}-redis
    #     image: redis:latest
    #     command: redis-server --appendonly yes
    #     volumes:
    #         - .docker/redis/data:/data
    #     ports:
    #         - 6379:6379
    #     networks:
    #         - proxy-network

    # ####################################################################################################
    # # DATABASE (MariaDB)
    # ####################################################################################################
    # db:
    #     container_name: ${APP_NAME}-mariadb
    #     image: mariadb:10.11
    #     ports:
    #         - 3306:3306
    #     volumes:
    #         - .docker/db/data:/var/lib/mysql
    #         - .docker/logs:/var/log/mysql
    #         - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    #         - .docker/db/sql:/docker-entrypoint-initdb.d
    #     environment:
    #         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    #         MYSQL_DATABASE: ${DB_DATABASE}
    #         MYSQL_USER: ${DB_USERNAME}
    #         MYSQL_PASSWORD: ${DB_PASSWORD}
    #     networks:
    #         - proxy-network

    ####################################################################################################
    # PostgreSQL (Optional)
    ####################################################################################################
    # db:
    #     container_name: ${APP_NAME}-postgres
    #     image: postgres:16
    #     ports:
    #         - 5432:5432
    #     volumes:
    #         - .docker/db/data:/var/lib/postgresql/data
    #         - .docker/db/sql:/docker-entrypoint-initdb.d
    #     environment:
    #         - POSTGRES_USER=${DB_USERNAME}
    #         - POSTGRES_PASSWORD=${DB_PASSWORD}
    #         - POSTGRES_DB=${DB_DATABASE}
    #     networks:
    #         - proxy-network

    ####################################################################################################
    # pgAdmin (Optional)
    ####################################################################################################
    # pgadmin:
    #     container_name: ${APP_NAME}-pgadmin
    #     image: dpage/pgadmin4:latest
    #     ports:
    #         - 5050:80
    #     environment:
    #         - PGADMIN_DEFAULT_EMAIL=admin@admin.com
    #         - PGADMIN_DEFAULT_PASSWORD=password
    #     depends_on:
    #         - ${APP_NAME}-postgres
    #     networks:
    #         - proxy-network

networks:
    proxy-network:
        external: true

